DROP TABLE IF EXISTS student;

CREATE TABLE student(
  student_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  birth_date DATE NOT NULL, 
  hair_color TEXT NOT NULL
);
