DROP TABLE IF EXISTS CHALLENGE; 
DROP TYPE IF EXISTS best_record; 
CREATE TYPE best_record AS ENUM('lowest', 'highest');

CREATE TABLE challenge(
    challenge_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    challenge_name TEXT NOT NULL,
    challenge_description TEXT NOT NULL,
    challenge_best_record best_record,
    units TEXT NOT NULL
);
