DROP TABLE IF EXISTS exchange CASCADE; 

CREATE TABLE exchange(
    exchange_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    student_id INTEGER REFERENCES student(student_id) ON DELETE CASCADE NOT NULL, 
    exchange_date DATE NOT NULL, 
    amount NUMERIC (6, 2) NOT NULL,
    note TEXT 
);