DROP TABLE IF EXISTS challenge_entry CASCADE; 

CREATE TABLE challenge_entry(
    challenge_entry_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    challenge_id INTEGER REFERENCES challenge(challenge_id) NOT NULL,
    student_id INTEGER REFERENCES student(student_id) ON DELETE CASCADE NOT NULL, 
    record INTEGER NOT NULL, 
    entry_date DATE NOT NULL, 
    notes TEXT 
);