DROP TABLE IF EXISTS student_subcommunity; 

CREATE TABLE student_subcommunity(
    student_subcommunity_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    student_id INTEGER REFERENCES student(student_id) NOT NULL,
    subcommunity_id INTEGER REFERENCES subcommunity(subcommunity_id) NOT NULL  
);