DROP TABLE IF EXISTS student_subcommunity CASCADE; 

CREATE TABLE student_subcommunity(
    student_subcommunity_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    student_id INTEGER REFERENCES student(student_id) ON DELETE CASCADE NOT NULL ,
    subcommunity_id INTEGER REFERENCES subcommunity(subcommunity_id) ON DELETE CASCADE NOT NULL
);